apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-depl
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: fadingfog/innotodo:kafka-consumer
          envFrom:
            - configMapRef:
                name: stats-config